x-runtime: &runtime
  hostname: localhost
  platform: linux/amd64
  privileged: true
  network_mode: host

x-ydb-node: &ydb-node
  image: cr.yandex/crptqonuodf51kdj7a7d/ydb:24.3.11.14
  restart: always
  <<: *runtime
  volumes:
    - ./ydb.yaml:/opt/ydb/cfg/config.yaml

name: ydb

services:
  static-0:
    <<: *ydb-node
    container_name: ydb-static-0
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "3135"
      - --mon-port
      - "8765"
      - --ic-port
      - "19001"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --node
      - static
      - --label
      - deployment=docker
    ports:
      - 3135:3135
      - 8765:8765
      - 19001:19001
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/3135"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s

  static-init:
    <<: *ydb-node
    restart: on-failure
    container_name: ydb-static-init
    command:
      - /opt/ydb/bin/ydbd
      - -s
      - grpc://localhost:3135
      - admin
      - blobstorage
      - config
      - init
      - --yaml-file
      - /opt/ydb/cfg/config.yaml
    depends_on:
      static-0:
        condition: service_healthy

  tenant-init:
    <<: *ydb-node
    restart: on-failure
    container_name: ydb-tenant-init
    command:
      - /opt/ydb/bin/ydbd
      - -s
      - grpc://localhost:3135
      - admin
      - database
      - /Root/testdb
      - create
      - ssd:1
    depends_on:
      static-init:
        condition: service_completed_successfully

  database-1:
    <<: *ydb-node
    container_name: ydb-database-1
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "3136"
      - --mon-port
      - "8766"
      - --ic-port
      - "19002"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --tenant
      - /Root/testdb
      - --node-broker
      - grpc://localhost:3135
      - --label
      - deployment=docker
    ports:
      - 3136:3136
      - 8766:8766
      - 19002:19002
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/3136"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      static-0:
        condition: service_healthy
      static-init:
        condition: service_completed_successfully
      tenant-init:
        condition: service_completed_successfully

  database-2:
    <<: *ydb-node
    container_name: ydb-database-2
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "3137"
      - --mon-port
      - "8767"
      - --ic-port
      - "19003"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --tenant
      - /Root/testdb
      - --node-broker
      - grpc://localhost:3135
      - --label
      - deployment=docker
    ports:
      - 3137:3137
      - 8767:8767
      - 19003:19003
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/3137"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      static-0:
        condition: service_healthy
      static-init:
        condition: service_completed_successfully
      tenant-init:
        condition: service_completed_successfully

  database-3:
    <<: *ydb-node
    container_name: ydb-database-3
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "3138"
      - --mon-port
      - "8768"
      - --ic-port
      - "19004"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --tenant
      - /Root/testdb
      - --node-broker
      - grpc://localhost:3135
      - --label
      - deployment=docker
    ports:
      - 3138:3138
      - 8768:8768
      - 19004:19004
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/3138"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      static-0:
        condition: service_healthy
      static-init:
        condition: service_completed_successfully
      tenant-init:
        condition: service_completed_successfully

  database-4:
    <<: *ydb-node
    container_name: ydb-database-4
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "3139"
      - --mon-port
      - "8769"
      - --ic-port
      - "19005"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --tenant
      - /Root/testdb
      - --node-broker
      - grpc://localhost:3135
      - --label
      - deployment=docker
    ports:
      - 3139:3139
      - 8769:8769
      - 19005:19005
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/3139"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      static-0:
        condition: service_healthy
      static-init:
        condition: service_completed_successfully
      tenant-init:
        condition: service_completed_successfully

  database-5:
    <<: *ydb-node
    container_name: ydb-database-5
    command:
      - /opt/ydb/bin/ydbd
      - server
      - --grpc-port
      - "3140"
      - --mon-port
      - "8770"
      - --ic-port
      - "19006"
      - --yaml-config
      - /opt/ydb/cfg/config.yaml
      - --tenant
      - /Root/testdb
      - --node-broker
      - grpc://localhost:3135
      - --label
      - deployment=docker
    ports:
      - 3140:3140
      - 8770:8770
      - 19006:19006
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/3140"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      static-0:
        condition: service_healthy
      static-init:
        condition: service_completed_successfully
      tenant-init:
        condition: service_completed_successfully
