services:
  ydb:
    image: ydbplatform/local-ydb:latest
    platform: linux/amd64
    container_name: ydb-local
    hostname: localhost
    environment:
      YDB_DEFAULT_LOG_LEVEL: NOTICE
      GRPC_TLS_PORT: "2135"
      GRPC_PORT: "2136"
      MON_PORT: "8765"
      YDB_USE_IN_MEMORY_PDISKS: "true"
    ports:
      - "2135:2135"
      - "2136:2136"
      - "8765:8765"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
      - "13133:13133"
      - "55679:55679"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [ otel-collector ]
  
  tempo:
    image: grafana/tempo:2.4.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200:3200"
    depends_on: [ otel-collector ]
    
  grafana:
    image: grafana/grafana:10.4.2
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on: [ prometheus, tempo ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "ydb-sdk-adonet-sample"
      YDB_ENDPOINT: "ydb:2136"
      YDB_DATABASE: "/local"
    depends_on: [ ydb, otel-collector ]